### ISSUE TITLE
Unable to build prod with: ERROR  TypeError: Cannot read property 'name' of undefined

### ISSUE THREAD

**Issue by tbock** [drewalth/dc-kayak#1]
![image](https://user-images.githubusercontent.com/4040295/64840707-4a0ffc00-d5b1-11e9-9e7d-ac11cfe7b256.png)

I think its pretty close to being able to be deployed but I hit this when building.  On my machine it actually still kicks out the dist folder.  However when it builds on heroku ... heroku get very angry and says you shall not pass.   I tried bumps some version of vue-router and vuex and removing anything that seemed to reference a name attribute... the error msg here isn't very helpful for me at least. 

Two other things.  First you might need to add a .env file to the root direction that looks exactly like .env.production I added (though I don't know enough about Vue to say this for sure).  Second I need admin permissions to the repo so I can setup the webhooks need to auto deploy to heroku.  

✌️

**Comment by drewalth** [comment]
Weird. Will look into this. Maybe something got missed when I stripped out laravel. Might just need to start a fresh new project.

Added you as a collaborator. Let me know if that does it.

**Comment by tbock** [comment]
Thank. I still don't see the settings tab... pretty sure you need to change my access from write to admin.

**Comment by drewalth** [comment]
Weird! I'm not seeing the write, read, admin dropdown. 

![image](https://user-images.githubusercontent.com/16584198/64877645-106dde00-d60f-11e9-819f-f4c6a9b90b64.png)

![image](https://user-images.githubusercontent.com/16584198/64877621-051ab280-d60f-11e9-8af8-0a48dab37966.png)

**Comment by tbock** [comment]
hah... i'm so used to our Organization account I forgot thats not an option on personal repos... no worries.  You will just have to set some things later.

**Comment by drewalth** [comment]
Fixed with the latest push. Another fresh start...
